version: '2'
services:
  postgres:
    image: "postgres:11-alpine"
    volumes:
    - "./db:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5435:5432"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

#  socket:
#    image: "socketcluster/socketcluster:v14.3.2"
##    environment:
##      - SOCKET_CLUSTER_HOST=${SOCKET_CLUSTER_HOST}
##      - SOCKET_CLUSTER_PORT=${SOCKET_CLUSTER_PORT}
##      - SOCKET_CLUSTER_IMPORT_PRODUCT_CHANNEL=${SOCKET_CLUSTER_IMPORT_PRODUCT_CHANNEL}
#    ports:
#      - "8100:8000"
#    restart: always
